[project]
title = "Project Rethabile"
version = "0.1.0"
port = 8501
slug = "project-rethabile"
entrypoint = "hello.py" 

[branding]
name = "Project Rethabile"
logo = "images/logo.png"
favicon = "data/magic_wand_icon_264766.png"
primaryColor = "#FFA07A"

[data.Mobiles_csv]
type = "csv"
path = "data/Mobiles.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"